export const progs = [
  {
    id: 1,
    name: "Наименование программы1",
    term: "4 года",
    paidAmount: 56,
    budgetAmount: 42,
    form: "Очное обучение",
    subjects: [{name: "Русский язык", id: 0}, {name: "Математика", id: 1}, {name: "Биология", id: 8}],
    institutes: [{name: "ИМЕН", id: 0}],
  },
  {
    id: 2,
    name: "Наименование программы2",
    term: "4 года",
    paidAmount: 56,
    budgetAmount: 42,
    form: "Заочное обучение",
    subjects: [{name: "Русский язык", id: 0}, {name: "История", id: 2}],
    institutes: [{name: "ЮИ", id: 1}],
  },
  {
    id: 3,
    name: "Наименование программы3",
    term: "4 года",
    paidAmount: 56,
    budgetAmount: 42,
    form: "Очное обучение",
    subjects: [{name: "Русский язык", id: 0}, {name: "Химия", id: 3}],
    institutes: [{name: "ИЖС", id: 3}],
  },
  {
    id: 4,
    name: "Наименование программы4",
    term: "4 года",
    paidAmount: 56,
    budgetAmount: 42,
    form: "Заочное обучение",
    subjects: [{name: "Русский язык", id: 0}, {name: "Химия", id: 3}],
    institutes: [{name: "ИЖС", id: 3}],
  }
];

export const description = {
  id: 1,
  name: "Наименование программы",
  term: "4 года",
  paidAmount: 56,
  budgetAmount: 42,
  subject: "Математика",
  institute: "ИМЕН",
  form: "Очное обучение",
  price: 150000,
  about: "О программе в html",
  disciplines: "Что я буду изучать в html",
  job: "Кем я буду работать в html",
};
